config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'towns/top' => 'towns#top'
  get 'towns/index' => 'towns#index'
  root 'towns#index'
  get 'towns/facility' => 'towns#facility'
  get 'towns/event' => 'towns#event'
  get 'towns/food' => 'towns#food'
  get 'towns/fukufuku' => 'towns#fukufuku'
  get 'towns/new' => 'towns#new'
  post 'towns' => 'towns#create'
  get 'towns/:id' => 'towns#show',as: 'town'
  patch 'towns/:id' => 'towns#update'
  delete 'towns/:id' => 'towns#destroy'
  get 'towns/:id/edit' => 'towns#edit', as:'edit_town'
  get 'towns/:town_id/likes' => 'likes#create'
  get 'towns/:town_id/likes/:id' => 'likes#destroy'
  resources :towns

  resources :towns do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :town
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :town
  belongs_to :user
  validates_uniqueness_of :town_id, scope: :user_id
end

app/models/town.rb
class Town < ApplicationRecord
    belongs_to :user, optional: true
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :towns
  has_many :towns, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_towns, through: :likes, source: :town
  has_many :towns, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  has_many :comments, dependent: :destroy

  def already_liked?(town)
    self.likes.exists?(town_id: town.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    town = Town.find(params[:town_id])
    comment = town.comments.build(comment_params) 
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) 
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(town_id: params[:town_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(town_id: params[:town_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :authenticate_user!, except: [:top, :facility, :food, :event, :fukufuku]
  def top
  end
  
  def facility
  end
  
  def index
    @towns= Town.all
    if params[:search] == nil
      @towns= Town.all
    elsif params[:search] == ''
      @towns= Town.all
    else
      @towns = Town.where("about LIKE ? ",'%' + params[:search] + '%')
    end
  end

  def new
    @town = Town.new
  end

  def create
    town = Town.new(town_params)
    town.user_id = current_user.id
    if town.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @town = Town.find(params[:id])
    @comments = @town.comments
    @comment = Comment.new
  end

  def edit
    @town = Town.find(params[:id])
  end

  def update
    town = Town.find(params[:id])
    if town.update(town_params)
      redirect_to :action => "show", :id => town.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    town = Town.find(params[:id])
    town.destroy
    redirect_to action: :index
  end

  def facility
  end

  def event
  end

  def food
  end

  def fukufuku
  end

  private
  def town_params
    params.require(:town).permit(:content, :about, :title, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<body class="noto-sans-japanese">
    <!--<header>
     <h1>福富町の人とお話しよう!</h1>
     <div class="header-list noto-sans-japanese">
     <ul>
      <li><%= link_to "HOME", towns_path %></li>
      <li><%= link_to "CREATE NEW POST",towns_new_path %></li>
     </ul>
     </div>
    </header>-->
    <main>
     <%= yield %>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&family=Noto+Serif+JP:wght@200..900&display=swap" rel="stylesheet">
</head>

<script src="https://kit.fontawesome.com/ca40daddfe.js" crossorigin="anonymous"></script>

app/views/towns/edit.html.erb
<div class=post_edit>
  <div class=post_edit_field>
    <div class=edit_title>
      投稿内容を変更する
    </div>
<%= form_for @town do |f| %>
    <%= f.text_field :about, :size => "50x2" %> 
    <button type="submit_tag" class="btn btn--orange btn--radius">編集する</button>
  <% end %>
  </div>
</div>

app/views/towns/event.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/event.css">
<body>


<div class="first-block7">
    <p class="eventlabel">
    イベント
    </p>
</div>
<div class="first-block7_1">
    <p class="spring">
    ４月
    </p>
</div>
<div class="first-block7_2">
    <%= image_tag "bus.jpg", class: "event-picture1" %>
    <%= image_tag "sinkan.jpg", class: "event-picture2" %>
</div>
<div class="first-block7_3">
    <p class="springdetail1">
    福富町ツアー　Byふくふく
    </p>
    <p class="springdetail2">
    <br>毎年４月にふくふく主催の福富町ツアーが行われます。
    <br>バスを１台貸し切り、福富町スポットを２か所巡ります🚌
    <br>みんなで話しながら福富町の自然を感じてみませんか？
    </p>
</div>
<div class="second-block7_1">
    <p class="august">
    ８月
    </p>
</div>
<div class="second-block7_2">
    <%= image_tag "hanabi.png", class: "event-picture3" %>
    <%= image_tag "syakunageko.jpg", class: "event-picture4" %>
    <%= image_tag "hanabi.png", class: "event-picture5" %>
</div>
<div class="second-block7_3">
    <p class="augustdetail1">
    しゃくなげ湖納涼花火大会
    <br>In 道の駅湖畔の里福富
    </p>
    <p class="augustdetail2">
    昨年第１回目が開催された地域のおまつり🎆
    <br>普段はただのダムですが
    <br>この夜だけは特別な場所に…
    <br>１５００発の花火とともに
    <br>素敵な夏のひと時を過ごしましょう✨
    </p>
</div>
<div class="third-block7_1">
    <p class="september">
    ９月
    </p>
</div>
<div class="third-block7_2">
    <%= image_tag "fes1.jpg", class: "event-picture6" %>
    <%= image_tag "fes2.jpg", class: "event-picture7" %>
    <%= image_tag "fes3.jpg", class: "event-picture8" %>
</div>
<div class="third-block7_3">
    <p class="septemberdetail1">
    アクアフェスタ
    <br>In 道の駅湖畔の里福富
    </p>
    <p class="septemberdetail2">
    ２日間で２７０００人が来場する
    <br>地域の最大のおまつり
    <br>ふくふくは「あいがもレース」を担当。
    <br>たくさんの出店や小さな水族館、展示等
    <br>きっとわくわくが見つかるはず
    <br>国土交通省より水資源功績者表彰を受賞しました。
    </p>
</div>

<footer>	
</footer>
</body>

app/views/towns/facility.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/facility.css">
<body>
  
<!--  コンテンツを一旦仮置きする  -->
  <div class="first-block2">
    <p class="facilitylabel">
      施設
    </p>
  </div>
  <div class="second-block2">
    <div class="box">
    <%= image_tag "facility1.jpg", class: "facility-picture1" %>
    <p class="mitinoekiname">道の駅湖畔の里福富</p>
    </div>
    <p class="mitinoeki">
      国道３７５号の道の駅であり、広島道の駅ランキング１位✨
    <br>福富ダムの人造湖であるしゃくなげ湖に面しており、
    <br>展望台からしゃくなげ湖と福富ダムのほか賀茂台地を
    <br>一望することができます。
    <br>また、キャンプ場や大規模の遊具等、家族連れの方に
    <br>嬉しい施設も充実しています！
    </p>
  </div>
  <div class="second-block3">
    <div class="border5">
    </div>
    <p class="fukkudetail">
      福と富からフック＆トミーと名付けました。
    <br>フックの頭には同町名産のエゴマの葉、
    <br>トミーにはシャクナゲの花が乗っています。
    <br>トミーが持っている旗には、道の駅で人気の
    <br>パンやソフトクリームのイラストが
    <br>入っています。
    </p>
    <%= image_tag "fukku.jpg", class: "facility-picture2" %>
    <div class="border6">
    </div>
  </div>
  <div class="third-block3">
    <div class="box2">
    <%= image_tag "miyabi.jpg", class: "facility-picture3" %>
    <p class="miyabiname">酵素風呂～雅～</p>
　　</div>
    <p class="miyabidetail">
    発酵熱を利用して身体を芯から温める酵素風呂を体験できます。
    <br>自然薬草と国産蜂蜜の恵みが生きている、こだわりの自家製酵素を
    <br>ふんだんに使ったお風呂です。
    <br>疲労回復や美肌効果に期待できます🎵
    <br>落ち着いたひと時を過ごしませんか？？
    <br>手ぶらOKで、予約必須です。
    <br>１回２５００円～
    <br>TEL：０９０－１１８４－７７９８
    </p>
  </div>
  <div class="interview">
    <div class="interview_photo">
    <%= image_tag "miyabikanban.jpg", class: "facility-picture33" %>
    <%= image_tag "okiyamasan.jpg", class: "facility-picture34" %>
    </div>
    <div class="interview_title">
      酵素風呂～雅～のオーナー　沖田勝美さんにインタビューしました！
    </div>
    <div class="interview_comment">
    酵素風呂をはじめたきっかけは交通事故がきっかけ。
    <br>交通事故に遭った時は、思考回路が０になるほど苦しい日常を送っていました。
    <br>しかし酵素風呂に入ったことで、気分が楽になったそう。
    <br>自衛隊、バイク屋さん、コンサル、保険などの多くの仕事をご経験した後、
    <br>酵素風呂をはじめました。
    <br>当時は奥様と離婚してでもやる気があったそうです。
    <br>なぜなら、自分が楽しいと感じることをやるべきだと考えていたから。
    <br>わたしにも、この強い思いを熱く語ってくださいました。
    <br>そんな強い思いを持った沖田さんが、水が綺麗な福富町で経営する酵素風呂～雅～
    <br>ぜひお越しください。
    </div>
  </div>

    
  </div>
  <div class="forth-block3">
    <div class="box3">
    <%= image_tag "cadore.jpg", class: "facility-picture4" %>
    <p class="cadorename">カドーレ</p>
　　</div>
    <p class="cadoredetail">
    牧場の搾りたてミルクで作ったジェラートやチーズ、
    <br>スイーツと、動物との触れ合いが楽しめる体験農場です。
    <br>場内のショップやカフェでは新鮮ミルクから作ったジェラート・焼きたてピザが人気です🎵
    <br>動物へのエサやり体験もできます🐄
    <br>TEL:０８２－４３０－１３８１
    </p>
  </div>
  <div class="forth-block4">
    <%= image_tag "usi.jpg", class: "facility-picture5" %>
    <%= image_tag "hituzi.jpg", class: "facility-picture5" %>
  </div>
  <div class="forth-block5">
  <div class="example">
    <hr>
  </div>
  <p class="animal">
    かわいい動物たちがあなたを待っています！
  </p>
  <div class="example2">
    <hr>
  </div>
  </div>
<!--  コンテンツはここまで  -->

  <footer>	
  </footer>
</body>

app/views/towns/food.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/food.css">

<div class="first-block8">
  <p class="foodlabel">食べ物</p>
</div>
<div class="first-block8_1">
  <p class="tokusanhin">
   福富町には少し変わった特産品があるそうです…
  </p>
  <p class="egoma">
   ▶荏胡麻（えごま）
  </p>
</div>
<div class="first-block8_2">
    <%= image_tag "egomalunch.jpg", class: "food-picture1" %>
    <p class="egomadetail1">
    こちらはふくふくが地域のお手伝いをした時に頂いた
    <br>「えごまランチ」
    <br>ほとんどのメニューでえごまが使用されている、贅沢なランチ
    <br>えごまはどんな料理にも合います。
    <br>普通のゴマよりもプチっとした食感がします。
    </div>
</div>
<div class="second-block8_1">
    <%= image_tag "egomadore2.jpg", class: "food-picture2" %>
    <p class="egomadetail2">
    ○えごまのドレッシング
    <br>さっぱりとしてサラダとの相性抜群です✨✨
    <br>普通のごまと比べてえごまは粒が大きいので、
    <br>よりごまの風味を感じることができます。
    <br>ふつうのゴマドレッシングももちろんおいしいですが
    <br>一風変わったえごまのドレッシングは
    <br>いかがですか？？
    </p>
</div>
<div class="second-block8_2">
    <div class="container">
    <p class="egomadetail3">
    えごまは、ごまのような形をしているシソ科の植物です。
    <br>種子から搾られたえごま油は「畑の青魚」と呼ばれるほどEPA、DHAの素となるα‐リノレン酸を豊富に含み、
    <br>免疫力強化や認知症予防、動脈硬化予防などに効果があるといわれています。
    <br>実（み）はクッキー、おむすび、サラダ、ゴマ和えなど幅広い料理に使えます。
    <br>ちなみに私はえごまクッキーが大好きです。
    <br>福富町はえごまが名産品です。
    <br>福富町のえごまは、無農薬で一粒一粒が手摘みで、熟練した農家が手間暇を掛けて作っています。
    </p>
    <div class="rectangle"></div>
    </div>
</div>
<div class="second-block8_3">
    <%= image_tag "hirameki.png", class: "food-picture3" %>
    <p class="egomadetail4">
    「えごま」という名前なのにシソ科なんだね！
    </p>
</div>
<div class="third-block8_1">
    <p class="quiz">
    ちょっと一息クイズ…
    </p>
    <div class="q">
    <p>Q:なんで福富町の名産品がえごまなの？？</p>
    </div>
    <div class="a">
    <p>A:利益が出やすいから。
          <br>コメの売上は10a当たり約150,000円とエゴマ10アール当たり約120,000円よりも
          <br>売上高が高いのですが、総費用との差し引きを考えるとえごまの方が利益が出ます。
          <br>かつてのわが国は、コメ一辺倒ではなく雑穀や野菜など、
          <br>数種類の農業を行うのが普通でした。
          <br>その後農業の大規模化が進んだわけですが、それでは地域による収益の格差が
          <br>大きくなるのが問題とされていました。
          <br>そこで特色ある作物を栽培することで、ブランド化して地域おこしにつなげよう
          <br>というのが福富町の狙いです。</p>
    </div>
</div>

<footer>
</footer>

app/views/towns/index.html.erb
<header>
  <p class="kouryuu">
  福富町の人と交流しよう！
  </p>
  <a href="http://localhost:3000/towns" class="btn-style-link10">ホーム</a>
  <a href="http://localhost:3000/towns/new" class="btn-style-link11">新規投稿</a>
</header>

<div class="towns-index">
  <p class="reserch">
  ◀ 投稿を検索 ▶
  </p>

 <%= form_tag({controller:"towns",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <button type="reserch_tag" class="btn btn--orange btn--radius">検索</button>
 <% end %>

<div class="list1">
  ◀ 投稿一覧 ▶
</div>

  <div class="towns-container">
    <% @towns.each do |t| %>

      <div class="towns">
      <div class="content">
      <%= t.about %>
      <%= image_tag t.image_url, size: "250x300" if t.image? %>
      </div>
      <div class="name">
      <%= link_to t.user.name, user_path(t.user.id) %>
      </div>

      <div class="heart">
    <% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
        <%= link_to town_like_path(id: t.id, town_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% else %>
        <%= button_to town_likes_path(id: t.id, town_id: t.id), method: :post do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
        <% end %>
    <% end %>
    <% else %>
    <i class="fas fa-heart"></i><%= t.likes.count %>
    <% end %>
    </div>
    <div class="time">
      <%= t.created_at %>
      </div>
      <div class="links">
        
      <!--<%= link_to "削除", town_path(t.id) %>-->
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "詳細へ", town_path(t.id) %>
      <%= link_to "編集", edit_town_path(t.id) %>
      <%= button_to "削除", town_path(t.id), method: :delete %>
      </div>
    <% end %>
    </div>


<% end %>
</div>

<div class="index_link">
<% if user_signed_in? %>
   <%= link_to "マイページへ", user_path(current_user.id), class:"field_input" %>
<% end %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn btn-secondary" %>
</div>
</div>

app/views/towns/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>

<header>
  <p class="kouryuu">
  福富町の人と交流しよう！
  </p>
  <a href="http://localhost:3000/towns" class="btn-style-link10">ホーム</a>
  <a href="http://localhost:3000/towns/new" class="btn-style-link11">新規投稿</a>
</header>

<div class="post-container">
 <div class=newpost>
  ◀ 新規投稿 ▶
  </div>
 <div class=newpost_detail>
  福富町についての疑問、興味が出たことを共有しよう🌟
  <br>福富町の方から返信が来ることも・・・？
  </div>

<%= form_for @town do |f| %>
  <div class="field10">
    <br>
    <%= f.label :投稿内容 %>
    <br>
    <%= f.text_field :about,size: "30x5" %>
    <!--<%= f.text_area :about, class: "hoge", size: "50x5" %>-->
    <br>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  
  <button type="submit_tag" class="btn btn--orange btn--radius">投稿する</button>
  <!--<a href="submit"value="投稿する"> class="btn btn--orange btn--radius">SUBMIT</a>-->
  <!--<%= f.submit "投稿する" %>-->
  <br>
<% end %>

<!--<%= link_to "投稿一覧に戻る", towns_index_path %>-->
</div>

app/views/towns/show.html.erb
<div class="post_detail">
  <div class="post_detail_field">
    <div class="post_detail_title">
    ◀ 投稿詳細 ▶
    </div>

<div class="detail_about">
  <%= @town.about %>
</div>

<div class="detail_time">
  <%= @town.created_at %>
</div>

<div class="detail_heart">
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@town) %>
        <%= button_to town_like_path(@town), method: :delete do %>
          <i class="fas fa-heart"></i><%= @town.likes.count %>
        <% end %>
      <% else %>
        <%= link_to town_likes_path(@town), method: :post do %>
          <i class="far fa-heart"></i><%= @town.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= @town.likes.count %>
    <% end %>
</div>

  <%= link_to "編集", edit_town_path(@town.id), class:"field_input" %>

<div class="liked_user">
<div class="liked_user_title">
いいねしたユーザー
</div>
<div class="liked_user_detail">
<% @town.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</div>
</div>

<div class="comment">
  <div class="comment-title">
  コメント一覧
  </div>
  <div class="comment-detail">
  <% @comments.each do |c| %>
    <div>
      <%= c.content %>
      <br>
      <%= c.user.email unless c.user.blank? %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@town, @comment], local: true) do |f| %>
      <%= f.text_area :content, class:"field_input200" %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "投稿一覧に戻る", towns_index_path, class:"field_input100" %>
</div>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) , class:"share_text" %><br />
<% end %>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name), class:"share_text" %><br />
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちらから", new_password_path(resource_name), class:"share_text" %><br />
<% end %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class=my_page>
  <div class=my_page_field>
  <div class=my_page_title>
  マイページ
  </div>

  <div class=my_page_name>
  名前 : <%= @user.name %>
  </div>
  <div class=my_page_mail>
  メールアドレス : <%= @user.email %>
  </div>
  <div class=my_page_profile>
  プロフィール : <%= @user.profile %>
  </div>

  <div class=your_post>
   あなたの投稿一覧 ：
<% @user.towns.each do |t| %>
  <%= t.about %>
<% end %>
  </div>

<div class=your_heart>
あなたがいいねした投稿一覧 ：
<% @user.liked_towns.each do |t| %>
  <%= t.about %>
<% end %>
</div>

<div class=link>
<% if current_user.id == @user.id %>
  <%= link_to "マイページを編集", edit_user_registration_path, class:"my_page_edit" %>
<% end %>

<div class=index_link>
<%= link_to "投稿一覧に戻る", towns_index_path, class:"back_index" %>
</div>
</div>
</div>
</div>